# Generated by Django 2.1.8 on 2019-07-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyerApp', '0003_order_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='goods_image',
            field=models.ImageField(default='/static/buyerapp/images/goods/goods001.jpg', upload_to='', verbose_name='商品图片'),
            preserve_default=False,
        ),
    ]
