# Generated by Django 2.1.8 on 2019-07-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyerApp', '0004_orderdetail_goods_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='goods_total',
            field=models.FloatField(verbose_name='单个商品总价'),
        ),
    ]
