# Generated by Django 2.1.8 on 2019-07-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_under',
            field=models.IntegerField(default=1, verbose_name='商品状态'),
        ),
        migrations.AlterField(
            model_name='store',
            name='type',
            field=models.ManyToManyField(to='StoreApp.StoreType', verbose_name='店铺和类型多对多'),
        ),
        migrations.AlterField(
            model_name='storetype',
            name='type_descripton',
            field=models.TextField(verbose_name='类型描述'),
        ),
    ]
