# Generated by Django 2.1.8 on 2019-07-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0004_auto_20190725_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='store_id',
            field=models.ManyToManyField(to='StoreApp.Store', verbose_name='商品 店铺 多对多'),
        ),
    ]
