# Generated by Django 2.1.8 on 2019-07-29 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0005_auto_20190729_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='store_id',
        ),
        migrations.AddField(
            model_name='goods',
            name='store_id',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, to='StoreApp.Store', verbose_name='商品店铺 '),
            preserve_default=False,
        ),
    ]
